---
# roles/ipxe_bootloader/tasks/main.yml
# Configura iPXE bootloader y menu para PXE clients

- name: Ensure ipxe package is installed
  apt:
    name: ipxe
    state: present

- name: Copy iPXE binaries to TFTP
  copy:
    src: "/usr/lib/ipxe/{{ item }}"
    dest: "{{ tftp_root }}/{{ item }}"
    remote_src: yes
    mode: '0644'
  loop:
    - ipxe.lkrn
    - ipxe.efi
  ignore_errors: yes  # Si no existen los binarios, continuamos

- name: Create iPXE boot script (boot.ipxe)
  template:
    src: boot.ipxe.j2
    dest: "{{ boot_dir }}/boot.ipxe"
    mode: '0644'
    owner: www-data
    group: www-data

- name: Create iPXE menu script (menu.ipxe)
  template:
    src: menu.ipxe.j2
    dest: "{{ boot_dir }}/menu.ipxe"
    mode: '0644'
    owner: www-data
    group: www-data

- name: Create machine configuration directory
  file:
    path: "{{ boot_dir }}/machines"
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Create example machine config (NAS)
  template:
    src: machine-example-nas.ipxe.j2
    dest: "{{ boot_dir }}/machines/nas.ipxe"
    mode: '0644'
    owner: www-data
    group: www-data

- name: Create example machine config (Proxmox)
  template:
    src: machine-example-proxmox.ipxe.j2
    dest: "{{ boot_dir }}/machines/proxmox.ipxe"
    mode: '0644'
    owner: www-data
    group: www-data

- name: Create example machine config (Edge)
  template:
    src: machine-example-edge.ipxe.j2
    dest: "{{ boot_dir }}/machines/edge.ipxe"
    mode: '0644'
    owner: www-data
    group: www-data

- name: Create pxelinux configuration (fallback)
  copy:
    content: |
      DEFAULT iPXE
      LABEL iPXE
        KERNEL ipxe.lkrn
        INITRD ipxe.lkrn
      TIMEOUT 50
      ONTIMEOUT iPXE
    dest: "{{ tftp_root }}/pxelinux.cfg/default"
    mode: '0644'
    owner: www-data
    group: www-data
